# Generated by Django 5.0.2 on 2024-03-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name_real',
            field=models.CharField(default='', max_length=50),
        ),
    ]
