# Generated by Django 5.0.2 on 2024-03-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_product_name_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name_real',
        ),
    ]
